/*
 * cylon-speech languages
 * http://cylonjs.com
 *
 * Copyright (c) 2016 The Hybrid Group
 * Licensed under the Apache 2.0 license.
*/

"use strict";

module.exports = {
  afrikaans: "af",
  aragonese: "an",
  bulgarian: "bg",
  bosnian: "bs",
  catalan: "ca",
  czech: "cs",
  welsh: "cy",
  danish: "da",
  german: "de",
  greek: "el",
  english: "en-gb",
  scottish: "en-sc",
  englishnorth: "en-uk-north",
  englishrp: "en-uk-rp",
  englishwmids: "en-uk-wmids",
  american: "en-us",
  westindies: "en-wi",
  esperanto: "eo",
  spanish: "es",
  spanishlatino: "es-la",
  estonian: "et",
  farsi: "fa",
  farsipinglish: "fa-pin",
  finnish: "fi",
  frenchbelgium: "fr-be",
  french: "fr",
  irishgaeilge: "ga",
  greekancient: "grc",
  hindi: "hi",
  croatian: "hr",
  hungarian: "hu",
  armenian: "hy",
  armenianwest: "hy-west",
  indonesian: "id",
  icelandic: "is",
  italian: "it",
  lojban: "jbo",
  georgian: "ka",
  kannada: "kn",
  kurdish: "ku",
  latin: "la",
  lithuanian: "lt",
  latvian: "lv",
  macedonian: "mk",
  malayalam: "ml",
  malay: "ms",
  nepali: "ne",
  dutch: "nl",
  norwegian: "no",
  punjabi: "pa",
  polish: "pl",
  brazil: "pt-br",
  portugal: "pt-pt",
  romanian: "ro",
  russian: "ru",
  slovak: "sk",
  albanian: "sq",
  serbian: "sr",
  swedish: "sv",
  swahili: "sw",
  tamil: "ta",
  turkish: "tr",
  vietnam: "vi",
  vietnamhue: "vi-hue",
  vietnamsgn: "vi-sgn",
  mandarin: "zh",
  cantonese: "zh-yue"
};
